import type { Spot } from "./spot-card"

export const spots: Spot[] = [
  {
    id: "hy-1",
    name: "Shah Ghouse",
    imageSrc: "/images/shah-ghouse.png",
    imageQuery: "Hyderabadi%20dum%20biryani%20closeup%20with%20fried%20onions%20and%20mint",
    rating: 4.5,
    spice: "Hot",
    priceLevel: "$$",
    isVegFriendly: true,
    tags: ["Hyderabadi", "Dum", "Spicy"],
    lat: 17.385,
    lon: 78.4867,
    address: "Hyderabad",
    url: "https://example.com/shah-ghouse",
  },
  {
    id: "hy-2",
    name: "Bawarchi RTC X Roads",
    imageSrc: "/images/bawarchi.png",
    imageQuery: "steaming%20biryani%20in%20handi%20restaurant%20ambience",
    rating: 4.3,
    spice: "Hot",
    priceLevel: "$$",
    isVegFriendly: true,
    tags: ["Legendary", "Hyderabadi", "Mutton"],
    lat: 17.4065,
    lon: 78.501,
    address: "Hyderabad",
  },
  {
    id: "che-1",
    name: "SS Hyderabad Biryani",
    imageSrc: "/images/ss-hyd.png",
    imageQuery: "Chennai%20biryani%20in%20banana%20leaf%20with%20raita",
    rating: 4.2,
    spice: "Medium",
    priceLevel: "$",
    isVegFriendly: true,
    tags: ["Chennai", "Budget", "Chicken"],
    lat: 13.0827,
    lon: 80.2707,
    address: "Chennai",
  },
  {
    id: "bl-1",
    name: "Meghana Foods",
    imageSrc: "/images/meghana.png",
    imageQuery: "biryani%20with%20fried%20chicken%20and%20boiled%20egg",
    rating: 4.4,
    spice: "Hot",
    priceLevel: "$$",
    isVegFriendly: true,
    tags: ["Bangalore", "Boneless", "Popular"],
    lat: 12.9716,
    lon: 77.5946,
    address: "Bengaluru",
  },
  {
    id: "kol-1",
    name: "Arsalan",
    imageSrc: "/images/arsalan.png",
    imageQuery: "Kolkata%20biryani%20with%20potato%20and%20egg",
    rating: 4.3,
    spice: "Mild",
    priceLevel: "$$",
    isVegFriendly: true,
    tags: ["Kolkata", "Potato", "Aromatic"],
    lat: 22.5726,
    lon: 88.3639,
    address: "Kolkata",
  },
  {
    id: "mum-1",
    name: "Jaffer Bhai’s Delhi Darbar",
    imageSrc: "/images/jaffer-bhai.png",
    imageQuery: "Mumbai%20biryani%20served%20with%20kebab%20platter",
    rating: 4.1,
    spice: "Medium",
    priceLevel: "$$",
    isVegFriendly: true,
    tags: ["Mumbai", "Mutton", "Rich"],
    lat: 19.076,
    lon: 72.8777,
    address: "Mumbai",
  },
  {
    id: "del-1",
    name: "Karim’s",
    imageSrc: "/images/karims.png",
    imageQuery: "Delhi%20old%20delhi%20biryani%20street%20style",
    rating: 4.2,
    spice: "Medium",
    priceLevel: "$$",
    isVegFriendly: false,
    tags: ["Delhi", "Heritage", "Mughlai"],
    lat: 28.6139,
    lon: 77.209,
    address: "New Delhi",
  },
  {
    id: "ko-1",
    name: "Paragon",
    imageSrc: "/images/paragon.png",
    imageQuery: "Malabar%20biryani%20with%20caramelized%20onions%20and%20cashews",
    rating: 4.4,
    spice: "Mild",
    priceLevel: "$$",
    isVegFriendly: true,
    tags: ["Kozhikode", "Malabar", "Fragrant"],
    lat: 11.2588,
    lon: 75.7804,
    address: "Kozhikode",
  },
]
